version: 2.1

jobs:
  build-test:
    docker:
      - image: circleci/python:3.8.8
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            make test
            make lint

workflows:
  main:
    jobs:
      - build-test
