version: 2.1

jobs:
  build-test:
    docker:
      - image: circleci/python:3.8.8
    steps:
      - checkout
      - run:
          command: |
            make setup
            . /home/circleci/.financial-analysis/bin/activate
            make test
            make lint

workflows:
  main:
    jobs:
      - build-test
