version: 2

jobs:
  build-test-lint:
    working_directory: /home/circleci
    docker:
      - image: circleci/python:3.8.8
    steps:
      - checkout
      - run:
          command: |
            make setup
            . /home/circleci/.financial-analysis/bin/activate
            make test
            make lint

workflows:
  main:
    jobs:
      - build-test-lint
